<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE persoane [
    <!ELEMENT persoane (persoana+)>
    <!ELEMENT persoana (nume, prenume, varsta, adresa, studii, experienta)>
    <!ATTLIST persoana id CDATA #REQUIRED>
    <!ELEMENT nume (#PCDATA)>
    <!ELEMENT prenume (#PCDATA)>
    <!ELEMENT varsta (#PCDATA)>
    <!ELEMENT adresa (strada, numar, localitate, judet, tara)>
    <!ELEMENT strada (#PCDATA)>
    <!ELEMENT numar (#PCDATA)>
    <!ELEMENT localitate (#PCDATA)>
    <!ELEMENT judet (#PCDATA)>
    <!ELEMENT tara (#PCDATA)>
    <!ELEMENT studii (#PCDATA)>
    <!ELEMENT experienta (#PCDATA)>
    ]>

<persoane>
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>
        <adresa>
            <strada>Strada</strada>
            <numar>nr 1</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>RO</tara>
        </adresa>
        <studii>facultate</studii>
        <experienta>0</experienta>
    </persoana>

    <persoana id="2">
        <nume>Ionescu</nume>
        <prenume>Petru</prenume>
        <varsta>42</varsta>
        <adresa>
            <strada>Strada 2</strada>
            <numar>nr 54</numar>
            <localitate>Vaslui</localitate>
            <judet>Vaslui</judet>
            <tara>RO</tara>
        </adresa>
        <studii>liceu</studii>
        <experienta>12 ani</experienta>
    </persoana>
</persoane>